# Generated by Django 2.1.7 on 2019-05-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StuAdmin1', '0006_merge_20190326_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='现楼号')),
                ('Floor_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='现层号')),
                ('Room_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='现房间号')),
                ('Bed', models.CharField(blank=True, max_length=10, null=True, verbose_name='现床位号')),
                ('Stu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuAdmin1.Stuinfo', verbose_name='原宿舍ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('Dorm_ID', models.CharField(help_text='宿舍号不能为空', max_length=100, primary_key=True, serialize=False, verbose_name='宿舍ID')),
                ('Building_Num', models.CharField(blank=True, max_length=100, null=True, verbose_name='楼号')),
                ('Floor_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='层号')),
                ('Room_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='房间号')),
                ('Dorm_Capacity', models.IntegerField(default=4, verbose_name='宿舍容量')),
                ('Actual_Num', models.IntegerField(default=0, verbose_name='实住人数')),
                ('Sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=4, null=True, verbose_name='性  别')),
            ],
        ),
        migrations.CreateModel(
            name='DormAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adjust_ID', models.IntegerField(default=1, help_text='调整宿舍号不能为空', verbose_name='调整ID')),
                ('Adjust_Time', models.DateTimeField(blank=True, max_length=64, null=True, verbose_name='调整时间')),
                ('Original_Dorm_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name='原宿舍ID')),
                ('Original_Building_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='原楼号')),
                ('Original_Floor_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='原层号')),
                ('Original_Room_Num', models.CharField(blank=True, max_length=10, null=True, verbose_name='原房间号')),
                ('Original_Bed', models.CharField(blank=True, max_length=10, null=True, verbose_name='原床位号')),
                ('Extra', models.CharField(blank=True, max_length=1000, null=True, verbose_name='调整备注说明')),
                ('Stu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuAdmin1.Stuinfo', verbose_name='原宿舍ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dormadjust',
            unique_together={('Adjust_ID', 'Stu_ID')},
        ),
    ]
