# Generated by Django 2.0.5 on 2018-08-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Start_Time', models.DateTimeField(blank=True, help_text='格式yyyy-mm-dd', max_length=64, null=True, verbose_name='开始时间')),
                ('Admin_End_Time', models.DateTimeField(blank=True, help_text='格式yyyy-mm-dd', max_length=64, null=True, verbose_name='结束时间')),
                ('If_Large_class', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=1, verbose_name='是否大类班')),
                ('Admin_Class_Remarks', models.CharField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Class_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('Institute_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Institute_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stuinfo',
            fields=[
                ('Stu_ID', models.CharField(help_text='学号不能为空', max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('Stu_Name', models.CharField(max_length=20, verbose_name='姓名')),
                ('Stu_Password', models.CharField(blank=True, default='123456', help_text='密码不能为空', max_length=20, null=True, verbose_name='密码')),
                ('Stu_Sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性  别')),
                ('Stu_BirthDate', models.DateTimeField(blank=True, max_length=64, null=True, verbose_name='出生日期')),
                ('Stu_Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭地址')),
                ('Stu_Telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('Stu_Hostel', models.CharField(blank=True, help_text='(9-201)', max_length=100, null=True, verbose_name='宿  舍')),
                ('Stu_Image', models.ImageField(upload_to='image/%Y/%m/%d/')),
                ('Stu_Class_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class1', to='StuAdmin1.Class', verbose_name='原班级 ')),
                ('Stu_Class_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class2', to='StuAdmin1.Class', verbose_name='现班级 ')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Teacher_Name', models.CharField(max_length=20)),
                ('Teacher_Telephone', models.CharField(blank=True, max_length=11, null=True)),
                ('Teacher_Office', models.CharField(blank=True, max_length=20, null=True)),
                ('Teacher_Office_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('Teacher_QQ', models.CharField(blank=True, max_length=20, null=True)),
                ('Teacher_Role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='Class_Institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StuAdmin1.Institute'),
        ),
        migrations.AddField(
            model_name='admin_class',
            name='Admin_Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuAdmin1.Class', verbose_name='班级ID'),
        ),
        migrations.AddField(
            model_name='admin_class',
            name='Admin_Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuAdmin1.Teacher', verbose_name='教师ID'),
        ),
    ]
