# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuAdmin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='Stu_BirthDate',
            field=models.DateTimeField(blank=True, max_length=64, null=True, verbose_name='出生日期'),
        ),
    ]
