# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuAdmin1', '0002_auto_20180808_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='Stu_Sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性  别'),
        ),
    ]
