# Generated by Django 2.0.7 on 2019-03-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StuAdmin1', '0005_auto_20180816_1618'),
        ('StuAdmin1', '0002_auto_20180719_1132'),
    ]

    operations = [
    ]
